on:
  pull_request:
    types: [closed]
jobs:
  CHANGELOG:
    if: github.event.pull_request.merged && contains(github.event.pull_request.title, 'RR-')
    runs-on: ubuntu-latest
    steps:
      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
      - uses: actions/checkout@v1
      - name: Commit CHANGELOG.md
        run: |
          git checkout main
          git pull
          sed -i '/Unreleased/a ${{ github.event.pull_request.title }}' CHANGELOG.md
          git config --local user.name "githab log"
          git add CHANGELOG.md
          git commit -m "Updating the CHANGELOG.md"
      - name: Push changes # push the output folder to your rep
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.base.ref }}
