on:
  push:
  pull_request:
    types: [opened, synchronize]

  print_title_of_pr:
    runs-on: ubuntu-latest
    steps:
      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo ${{ github.event.pull_request.title }} >> CHANGELOG.md
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating CHANGELOG.md"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
